# This workflow will build the jar with Gradle and create a new release with it.
name: Build JAR
on: [push]
permissions:
  actions: read
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean package --file pom.xml
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{github.run_number}}
          files: target/CommandPanels-DEV.jar